### ISSUE TITLE
Memory leak problem as of Vlang v0.3?

### ISSUE THREAD

**Issue by ghost** [holder66/hamnn#10]
In the Readme there is a section called 'Memory leak problem':  
https://github.com/holder66/HamNN#memory-leak-problem

Is that section still relevant? I'm asking because in Vlang v0.3 one of the things listed in the changelog was:  
"Programs built with the V compiler no longer leak memory by default."  
(https://github.com/vlang/v/discussions/14895)

**Comment by holder66** [comment]
Thank you for letting me know, Ted! Much appreciated! 

Henry

**Comment by holder66** [comment]
Thank you, Ted!
